### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pathumego** [mooniak/gemunu-libre-font#13]
- [x] Credits on `README.md`
- [x] Review Sinhala
- [x] Review Latin
- [x] Reveiw Tamil
- [x] Credits on `FONTLOG.md`
- [x] Credits on  `/features/tables.fea`
- [x] Copyright notice on `OFL.txt`
- [x] Copyright on SFD sources
- [x] Copyright on UFO sources
- [x] Copyright on `/features/tables.fea`
- [x] Version on `FONTLOG.md`
- [x] Version on  `/features/tables.fea`
- [x] Description (Names/ Dates)
- [x] Fontlog
- [x] Check Issue Tracker for Release Milestone
- [ ] Final Feature Testing
- [ ] rc-1 Testing
- [ ] Make final binarieries with OFL

**Comment by davelab6** [comment]
> Copyright notice on Repo READM.md

Not needed

**Comment by davelab6** [comment]
The notices should match. For projects with many copyright holders, its good to set it up like https://github.com/NDISCOVER/Arima-Font

**Comment by davelab6** [comment]
For all projects involving trademarks - eg https://github.com/mooniak/ayanna-font/blob/master/TRADEMARKS.md - please email me the tm permission
