### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by pathumego** [mooniak/gemunu-libre-font#2]
- [ ] Credits on `README.md`
- [ ] Credits on `FONTLOG.md`
- [x] Credits on  `/features/tables.fea`
- [ ] Copyright notice on Repo `READM.md`
- [x] Copyright notice on `OFL.txt`
- [ ] Copyright on SFD sources
- [ ] Copyright on UFO sources
- [ ] Copyright on `/features/tables.fea`
- [ ] Version on `FONTLOG.md`
- [ ] Version on  `/features/tables.fea`
- [ ] Description (Names/ Dates)
- [ ] Fontlog
- [ ] Check Issue Tracker for Release Milestone
- [ ] Final Feature Testing
- [ ] rc-1 Testing
